
/* Automatic generated by './bin/build-router.js' */
import entry from './index.vue'

export default {
  path: '/',
  component: entry,
  children: [
    {
      path: '',
      name: 'index',
      component: () => import('./index.md'),
    },
    {
        path: 'back-to-top',
        name: 'back-to-top',
        component: () => import('./doc-mds/back-to-top.md'),
      },
      {
        path: 'button',
        name: 'button',
        component: () => import('./doc-mds/button.md'),
      },
      {
        path: 'card',
        name: 'card',
        component: () => import('./doc-mds/card.md'),
      },
      {
        path: 'cell',
        name: 'cell',
        component: () => import('./doc-mds/cell.md'),
      },
      {
        path: 'checkbox',
        name: 'checkbox',
        component: () => import('./doc-mds/checkbox.md'),
      },
      {
        path: 'header',
        name: 'header',
        component: () => import('./doc-mds/header.md'),
      },
      {
        path: 'image-preview',
        name: 'image-preview',
        component: () => import('./doc-mds/image-preview.md'),
      },
      {
        path: 'layout',
        name: 'layout',
        component: () => import('./doc-mds/layout.md'),
      },
      {
        path: 'loading',
        name: 'loading',
        component: () => import('./doc-mds/loading.md'),
      },
      {
        path: 'model',
        name: 'model',
        component: () => import('./doc-mds/model.md'),
      },
      {
        path: 'popup',
        name: 'popup',
        component: () => import('./doc-mds/popup.md'),
      },
      {
        path: 'radio',
        name: 'radio',
        component: () => import('./doc-mds/radio.md'),
      },
      {
        path: 'scroll',
        name: 'scroll',
        component: () => import('./doc-mds/scroll.md'),
      },
      {
        path: 'select',
        name: 'select',
        component: () => import('./doc-mds/select.md'),
      },
      {
        path: 'slide',
        name: 'slide',
        component: () => import('./doc-mds/slide.md'),
      },
      {
        path: 'slip',
        name: 'slip',
        component: () => import('./doc-mds/slip.md'),
      },
      {
        path: 'switch',
        name: 'switch',
        component: () => import('./doc-mds/switch.md'),
      },
      {
        path: 'tab',
        name: 'tab',
        component: () => import('./doc-mds/tab.md'),
      },
      {
        path: 'toast',
        name: 'toast',
        component: () => import('./doc-mds/toast.md'),
      },
  ]
}
