
/* Automatic generated by './build/build-components.js' */
import backToTop from './components/back-to-top/back-to-top.vue'
import button from './components/button/button.vue'
import card from './components/card/card.vue'
import cell from './components/cell/cell.vue'
import header from './components/header/header.vue'
import imagePreview from './components/image-preview/image-preview.vue'
import layout from './components/layout/layout.vue'
import $loading from './components/loading'
import model from './components/model/model.vue'
import $popup from './components/popup'
import scroll from './components/scroll/scroll.vue'
import slide from './components/slide/slide.vue'
import slip from './components/slip/slip.vue'
import tab from './components/tab/tab.vue'
import $toast from './components/toast'

const components = [
  backToTop,
  button,
  card,
  cell,
  header,
  imagePreview,
  layout,
  model,
  scroll,
  slide,
  slip,
  tab
]

// JS组件
const jsComponents = {
  $loading,
  $popup,
  $toast,
}

const install = function (Vue) {
  // 全局注册普通组件
  Object.keys(components).map(key => Vue.component(components[key].name, components[key]))
  // 全局注册JS组件
  Object.assign(Vue.prototype, jsComponents)
}

export default {
  install
}
