
/* Automatic generated by './build/build-components.js' */
import BackToTop from './components/back-to-top/back-to-top.vue'
import Button from './components/button/button.vue'
import Card from './components/card/card.vue'
import Cell from './components/cell/cell.vue'
import Checkbox from './components/checkbox/checkbox.vue'
import Header from './components/header/header.vue'
import ImagePreview from './components/image-preview/image-preview.vue'
import Layout from './components/layout/layout.vue'
import $loading from './components/loading'
import Model from './components/model/model.vue'
import $popup from './components/popup'
import Radio from './components/radio/radio.vue'
import Scroll from './components/scroll/scroll.vue'
import Select from './components/select/select.vue'
import Slide from './components/slide/slide.vue'
import Slip from './components/slip/slip.vue'
import Switch from './components/switch/switch.vue'
import Tab from './components/tab/tab.vue'
import $toast from './components/toast'

const components = [
  BackToTop,
  Button,
  Card,
  Cell,
  Checkbox,
  Header,
  ImagePreview,
  Layout,
  Model,
  Radio,
  Scroll,
  Select,
  Slide,
  Slip,
  Switch,
  Tab
]

// JS组件
const jsComponents = {
  $loading,
  $popup,
  $toast,
}

const install = function (Vue) {
  // 全局注册普通组件
  Object.keys(components).map(key => Vue.component(components[key].name, components[key]))
  // 全局注册JS组件
  Object.assign(Vue.prototype, jsComponents)
}

export default {
  install
}
