
/* Automatic generated by './build/build-router.js' */

import Vue from 'vue'
import VueRouter from 'vue-router'
import demoRoutes from './demo/routes' // demo
import entry from './app.vue'

Vue.use(VueRouter)

const routes = [
  {
    path: '/',
    component: entry,
    children: [
      {
        path: '',
        name: '',
        component: () => import('./pages/index.md'),
      },
      {
        path: 'back-to-top',
        name: 'back-to-top',
        component: () => import('./pages/doc-mds/back-to-top.md'),
      },
      {
        path: 'button',
        name: 'button',
        component: () => import('./pages/doc-mds/button.md'),
      },
      {
        path: 'card',
        name: 'card',
        component: () => import('./pages/doc-mds/card.md'),
      },
      {
        path: 'cell',
        name: 'cell',
        component: () => import('./pages/doc-mds/cell.md'),
      },
      {
        path: 'header',
        name: 'header',
        component: () => import('./pages/doc-mds/header.md'),
      },
      {
        path: 'image-preview',
        name: 'image-preview',
        component: () => import('./pages/doc-mds/image-preview.md'),
      },
      {
        path: 'layout',
        name: 'layout',
        component: () => import('./pages/doc-mds/layout.md'),
      },
      {
        path: 'loading',
        name: 'loading',
        component: () => import('./pages/doc-mds/loading.md'),
      },
      {
        path: 'model',
        name: 'model',
        component: () => import('./pages/doc-mds/model.md'),
      },
      {
        path: 'popup',
        name: 'popup',
        component: () => import('./pages/doc-mds/popup.md'),
      },
      {
        path: 'scroll',
        name: 'scroll',
        component: () => import('./pages/doc-mds/scroll.md'),
      },
      {
        path: 'slide',
        name: 'slide',
        component: () => import('./pages/doc-mds/slide.md'),
      },
      {
        path: 'slip',
        name: 'slip',
        component: () => import('./pages/doc-mds/slip.md'),
      },
      {
        path: 'tab',
        name: 'tab',
        component: () => import('./pages/doc-mds/tab.md'),
      },
      {
        path: 'toast',
        name: 'toast',
        component: () => import('./pages/doc-mds/toast.md'),
      },
    ]
  },
  demoRoutes,
  {
    path: '*',
    redirect: '/',
  }
]

const router = new VueRouter({
  routes
})

const layers = document.getElementsByClassName('tui-mask-bg')

router.beforeEach((to, from, next) => {
  // 删除顽固节点
  Array.from(layers).forEach((vv) => {
    vv.parentNode.removeChild(vv)
  })
  document.title = to.name || document.title
  next()
})

export default router
